[project]
name = "Draco"
version = "0.6.0"
url = "https://github.com/guitsaru/draco"

[package]
requires = [
	"lib/draco.rb",
	"app/components/index.rb",
	"app/entities/index.rb",
	"app/systems/index.rb",
	"app/worlds/index.rb"
]

[package.installs]
"template/components/index.rb" = "app/components/index.rb"
"template/entities/index.rb" = "app/entities/index.rb"
"template/systems/index.rb" = "app/systems/index.rb"
"template/worlds/index.rb" = "app/worlds/index.rb"
